- name: APR
  get_url: url={{ apr_url }}apr-{{ apr_version }}.tar.gz dest={{ work_dir }}

- name: unpack apr
  command: tar xzvf {{ work_dir }}/apr-{{ apr_version }}.tar.gz -C {{ work_dir }}

- name: apr configured.
  command: chdir={{ work_dir }}/apr-{{ apr_version }} ./configure --prefix={{ work_dir }}/apr-{{ apr_version }}

- name: apr compile.
  command: chdir={{ work_dir }}/apr-{{ apr_version }} make

#- name: apr test
#  command: chdir={{ work_dir }}/apr-{{ apr_version }} make test

- name: apr installed.
  command: chdir={{ work_dir }}/apr-{{ apr_version }} make install

- name: APR_UTIL
  get_url: url={{ apr_util_url }}apr-util-{{ apr_util_version }}.tar.gz dest={{ work_dir }}

- name: unpack apr_util
  command: tar xzvf {{ work_dir }}/apr-util-{{ apr_util_version }}.tar.gz -C {{ work_dir }}

- name: apr_util configured.
  command: chdir={{ work_dir }}/apr-util-{{ apr_util_version }} ./configure --prefix={{ work_dir }}/apr-util-{{ apr_util_version }} --with-apr={{ work_dir }}/apr-{{ apr_version }}

- name: apr_util compile.
  command: chdir={{ work_dir }}/apr-util-{{ apr_util_version }} make

#- name: apr_util test
#  command: chdir={{ work_dir }}/apr-util-{{ apr_util_version }} make test

- name: apr_util installed.
  command: chdir={{ work_dir }}/apr-util-{{ apr_util_version }} make install

- name: httpd source download.
  get_url: url={{ httpd_source_url }} dest={{ work_dir }}

- name: httpd archive unpackage.
#unarchive: src={{ work_dir }}/{{ httpd_package_name }}.tar.gz dest={{ work_dir }}
  command: tar xzvf {{ work_dir }}/{{ httpd_package_name }}.tar.gz -C {{ work_dir }}

- name: httpd configured.
#  command: chdir={{ work_dir }}/{{ httpd_package_name }} ./configure --prefix="{{ install_dir }}"/"{{ httpd_package_name }}" --with-apr={{ work_dir }}/apr-{{ apr_version }} --with-apr-util={{ work_dir }}/apr-util-{{ apr_util_version }} --enable-so --enable-ssl

  command: chdir={{ work_dir }}/{{ httpd_package_name }} ./configure --with-apr={{ work_dir }}/apr-{{ apr_version }} --with-apr-util={{ work_dir }}/apr-util-{{ apr_util_version }} --enable-so --enable-ssl

- name: httpd compile.
  command: chdir={{ work_dir }}/{{ httpd_package_name }} make
#  command: cd {{ install_dir }}/{{ httpd_package_name }} make

- name: httpd installed.
# command: chdir={{ work_dir }}/porg-{{ porgver }} porg -lp {{ httpd_package_name }} "make install"
# command: cd {{ work_dir }}/porg-{{ porgver }} && porg -lp {{ httpd_package_name }} "make install"
  command: chdir={{ work_dir }}/{{ httpd_package_name }} make install

#- name: httpd serverroot symlinks set.
#  file: src={{ install_dir }}/{{ httpd_package_name }} dest={{ install_dir }}/apache2 state=link
#
#- name: make apache group.
#  group: name=apache gid=48 system=yes
#
#- name: make apache user.
#  user: name=apache uid=48 group=apache home={{ install_dir }}/apache2 shell=/sbin/nologin system=yes

#- name: register of init script.
#  copy: >
#    src={{ base_dir }}/templates/httpd.init-script
#    dest=/etc/init.d/httpd
#    mode=0755

#- name: httpd service of startup register.
#  service: name=httpd enabled=yes

#- name: httpd log rotate.
#  copy: >
#    src={{ base_dir }}/templates/httpd.logrotate
#    dest=/etc/logrotate.d/httpd
#    mode=0644
