---
galaxy_info:
  author: myname
  description: Setup ja_jp locale
  license: MIT
  min_ansible_version: 1.2

  platforms:
  - name: Debian
    versions:
    - wheezy

  categories:
  - packaging
  - system

dependencies: []
