- include: common.yml
- include: oreore.yml
- include: build-apache.yml
#- include: webservers.yml
#- include: appservers.yml
#- include: dbservers.yml
#- include: rsyslog.yml
#- include: apache2.yml
