---
- name: Restart apache
  service:
    name: apache2
    state: restarted

- name: Reload apache
  service:
    name: apache2
    state: reloaded

- name: Reload nrpe
  service: name=nagios-nrpe-server state=reloaded

- name: Restart nrpe
  service: name=nagios-nrpe-server state=restarted
