- name: Get latest peco version
  shell: >
    curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^Location:/{print $NF}'
  register: peco_latest_version

- name: Download latest peco
  get_url: url=https://github.com/peco/peco/releases/download/"{{ peco_latest_version.stdout }}"/peco_linux_amd64.tar.gz dest=~/tmp/peco_linux_amd64.tar.gz 

- name: Extract peco
#  unarchive: 
#    src="~/tmp/peco_linux_amd64.tar.gz"
#    dest="~/tmp/"
  command: tar xzvf ~/tmp/peco_linux_amd64.tar.gz -C ~/tmp/

- name: Copy to /usr/bin/
  sudo: yes
  command: cp /home/oreore/tmp/peco_linux_amd64/peco /usr/bin/
