- name: install yum packages
  yum: name={{ item }} state=latest
  with_items:
    - sudo
    - passwd
    - mlocate
#    - mod_ssl
    - openssl
    - openssl-devel
    - firewalld

- name: LC
  command: localedef -f UTF-8 -i ja_JP /usr/lib/locale/ja_JP.utf8

- name: locale
  command: localectl set-locale LANG=ja_JP.utf8

- name: timezone tokyo
  command: timedatectl set-timezone Asia/Tokyo

- name: keymap
  command: localectl set-keymap jp106

- name: modified access.conf
  lineinfile: >-
    dest=/etc/security/access.conf
    state=present
    regexp="-:ALL EXCEPT wheel {{ user }}"
    line='-:ALL EXCEPT wheel {{ user }}:ALL'

- name: modified pam.d sshd
  lineinfile: >-
    dest=/etc/pam.d/sshd
    state=present
    backrefs=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - regexp: 'nologin'
      line: '#account    required     pam_nologin.so'

- name: add pam_access.so
  lineinfile: dest=/etc/pam.d/sshd state=present regexp="pam_access.so" line='account    required     /usr/lib64/security/pam_access.so'

- name: restart sshd
  service: name=sshd state=restarted
