---
    - name: add a new user
      user: name="{{ user }}" password="{{password}}" state=present
    - name: add a sudo user
      lineinfile: "dest=/etc/sudoers backup=yes state=present regexp='^oreore' line='oreore ALL=(ALL) NOPASSWD: ALL'"

#    - name: dowanload pubkey from Github and placed as authorized_keys
#      get_url: url=https://github.com/"{{ key_name }}".keys dest=~/tmp/"{{ key_name }}".authorized_keys
#      delegate_to: 127.0.0.1
    - name: Create authorized_keys from the file that just downloaded
      authorized_key: user="{{ user }}" key="{{ lookup('file', '~/.ssh/id_rsa_github.pub') }}"

    - name: Change defalt shell
      user: name="{{ user }}" shell="{{ shell }}"
      tags: default-shell

